/* SIE CONFIDENTIAL
PlayStation(R)5 Programmer Tool Runtime Library Release 11.00.00.40-00.00.00.0.1
* Copyright (C) 2021 Sony Interactive Entertainment Inc.
* 
*/

#pragma once

#include <agc.h>

namespace psfx
{

struct DofConfiguration
{
   // Maximum dimensions of the texture that will have DoF applied. Actual dimensions are
   // specified each frame and can be dynamically adjusted.
   uint32_t max_target_width;
   uint32_t max_target_height;
};

struct MemoryPool;
struct MemoryRequirement;

struct DofRuntimeOption
{
   // Source/destination texture size.
   uint32_t target_width;
   uint32_t target_height;

   // Linear depth texture. Can be generated by psfx_linearize_depth, or an existing one
   // generated outside of psfx can be used (may need to modify shader code if this is
   // encoded differently to how psfx encodes it).
   sce::Agc::Core::Texture source_linear_depth;

   sce::Agc::Core::Texture source;
   float near_cocMin = 0.0f;
   float near_cocMax = 0.0f;
   float far_cocMin = 0.0f;
   float far_cocMax = 0.0f;
   float near_plane_distance;
   float far_plane_distance;
};

struct DofContext;

void dof_configuration_init(DofConfiguration& conf);
int dof_compute_memory_requirement(DofConfiguration const& conf, MemoryRequirement& memory_pool);

DofContext* dof_initialize(DofConfiguration const& conf, MemoryPool const& memory_pool);
void dof_terminate(DofContext* ctx);

void dof_apply(DofContext* ctx, sce::Agc::DrawCommandBuffer* dcb, DofRuntimeOption const& options);
void dof_apply(DofContext* ctx, sce::Agc::AsyncCommandBuffer* dcb, DofRuntimeOption const& options);

}
