/* SIE CONFIDENTIAL
PlayStation(R)5 Programmer Tool Runtime Library Release 11.00.00.40-00.00.00.0.1
* Copyright (C) 2021 Sony Interactive Entertainment Inc.
* 
*/

#pragma once

#include <agc.h>

namespace psfx
{

struct MemoryPool;
struct MemoryRequirement;

struct MotionBlurConfiguration
{
   // Maximum dimensions of the texture that will be blurred. Actual dimensions are specified each
   // frame and can be dynamically adjusted.
   uint32_t max_target_width;
   uint32_t max_target_height;
};

struct MotionBlurRuntimeOption
{
   // Source/destination texture size.
   uint32_t target_width;
   uint32_t target_height;

   // Linear depth texture. Can be generated by psfx_linearize_depth, or an existing one
   // generated outside of psfx can be used (may need to modify shader code if this is
   // encoded differently to how psfx encodes it).
   sce::Agc::Core::Texture source_linear_depth;

   // Velocity texture. Each pixel is expected to contain an X/Y texture coordinate delta for
   // that pixel from its position in the previous frame.
   sce::Agc::Core::Texture source_velocity;

   // Texture that the effect will be applied to.
   sce::Agc::Core::Texture destination;

   // Time delta since the previous frame.
   float delta_time;

   // Camera exposure time.
   float exposure_time = 0.03f;

   // Projection parameters.
   float near_plane_distance;
   float far_plane_distance;
};

struct MotionBlurContext;

void motion_blur_configuration_init(MotionBlurConfiguration& conf);

int motion_blur_compute_memory_requirement(const MotionBlurConfiguration& conf, MemoryRequirement& requirement);

MotionBlurContext* motion_blur_initialize(const MotionBlurConfiguration& conf, const MemoryPool& memory_pool);
void motion_blur_terminate(MotionBlurContext* ctx);

void motion_blur_apply(MotionBlurContext* ctx, sce::Agc::AsyncCommandBuffer* acb, const MotionBlurRuntimeOption& options);
void motion_blur_apply(MotionBlurContext* ctx, sce::Agc::DrawCommandBuffer* dcb, const MotionBlurRuntimeOption& options);

}
