/* SIE CONFIDENTIAL
PlayStation(R)5 Programmer Tool Runtime Library Release 11.00.00.40-00.00.00.0.1
* Copyright (C) 2021 Sony Interactive Entertainment Inc.
* 
*/

#pragma once

#include <Agc.h>

namespace psfx
{

enum BufferSemantic
{
   k_linear_depth = 0,
   k_linear_interleaved_depth,
   k_ao,
   k_ao_interleaved,
   k_nothing,
};

struct SsaoConfiguration
{
   // Maximum dimensions of the texture that will have SSAO applied. Actual dimensions are
   // specified each frame and can be dynamically adjusted.
   uint32_t max_target_width;
   uint32_t max_target_height;

   uint32_t downsample_steps;
   bool use_interleaved;
   bool dynamic_resolution;
   // Possible options
   // bool support_4k_checker_board;
   // uint layer count
   // bool use details (normal) for mip0
   // bool generate ss specular occlusion;
};

struct MemoryPool;
struct MemoryRequirement;

struct SsaoRuntimeOption
{
   // Source/destination texture size.
   uint32_t target_width;
   uint32_t target_height;

   // Linear depth texture. Can be generated by psfx_linearize_depth, or an existing one
   // generated outside of psfx can be used (may need to modify shader code if this is
   // encoded differently to how psfx encodes it).
   sce::Agc::Core::Texture source_linear_depth;

   sce::Agc::Core::Texture destination;

   float near_plane_distance;
   float far_plane_distance;
   float upscale_threshold = 0.05f;
   float log_blur_scale = 0.1f;
   float reject_falloff;
   float fov_x = 1.f; // tan of fov/2
   float fov_y = 1.f;
};

struct SsaoContext;

void ssao_configuration_init(SsaoConfiguration& conf);
int ssao_compute_memory_requirement(SsaoConfiguration const& conf, MemoryRequirement& memory_pool);

SsaoContext* ssao_initialize(SsaoConfiguration const& conf, MemoryPool const& memory_pool);
void ssao_terminate(SsaoContext* ctx);

void ssao_apply(SsaoContext* ctx, sce::Agc::DrawCommandBuffer* dcb, SsaoRuntimeOption const& options, volatile sce::Agc::Label* finished = 0 );
void ssao_apply(SsaoContext* ctx, sce::Agc::AsyncCommandBuffer* dcb, SsaoRuntimeOption const& options, volatile sce::Agc::Label* finished = 0);

sce::Agc::Core::Texture* ssao_get_buffer(SsaoContext* ctx, BufferSemantic semantic, uint32_t index);

}
